### ISSUE TITLE
Back end page not working on M1

### ISSUE THREAD

**Issue by edwardfraser2002** [github/dotnet-codespaces#9]
I have created a new code space using this template on Chrome and Safari on my M1 Mac and I have not been able to get ithe backend page to work
 Chrome seemed to give no reason but Safari gave me the following:

Exception has occurred: CLR/System.IO.IOException
An unhandled exception of type 'System.IO.IOException' occurred in System.Private.CoreLib.dll: 'Failed to bind to address http://127.0.0.1:8080: address already in use.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.Net.Sockets.SocketException : Address already in use
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()

**Comment by Servingmen69** [comment]
> I have created a new code space using this template on Chrome and Safari on my M1 Mac and I have not been able to get ithe backend page to work Chrome seemed to give no reason but Safari gave me the following:
> 
> Exception has occurred: CLR/System.IO.IOException An unhandled exception of type [`'System.IO.IOException'`]([url]
/)) occurred in System.Private.CoreLib.dll: 'Failed to bind to address http://127.0.0.1:8080: address already in use.' Inner exceptions found, see $exception in variables window for more details. Innermost exception System.Net.Sockets.SocketException : Address already in use at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress) at System.Net.Sockets.Socket.Bind(EndPoint localEP) at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint) at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()

``

**Comment by lkhg** [comment]
![bcgame sk-qrcode (3)](https://github.com/github/dotnet-codespaces/assets/7334687/6600f6bd-e20a-4109-ad31-6d5fb1efdf49)

**Comment by valeriazagontova** [comment]
/

**Comment by timheuer** [comment]
Closing as no activity.
